services:
  postgres:
    image: postgres:15-alpine
    container_name: prodyo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-prodyo_db}
      POSTGRES_USER: ${DB_USER:-prodyo_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-prodyo_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prodyo-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: prodyo-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@prodyo.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - prodyo-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prodyo-api
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-prodyo_db}
      DB_USER: ${DB_USER:-prodyo_user}
      DB_PASSWORD: ${DB_PASSWORD:-prodyo_password}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - prodyo-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  prodyo-network:
    driver: bridge


